# Generated by Django 5.1.2 on 2024-10-25 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_question_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 1, 11, 5, 8, 409119), verbose_name='Дата окончания'),
        ),
    ]
